In [4]:
#Задача1 Выполнить операции над матрицами
import numpy as np

In [5]:
a = np.array([[1, 2, 1], [-2, 1 ,1]])
a

array([[ 1,  2,  1],
       [-2,  1,  1]])

In [6]:
b = np.array([[3, 1], [-1, 0], [2, 4]])
b

array([[ 3,  1],
       [-1,  0],
       [ 2,  4]])

In [7]:
c = np.array([[-2, 2], [1, -1], [1, 2]])
c

array([[-2,  2],
       [ 1, -1],
       [ 1,  2]])

In [8]:
print(a + 2*np.transpose(b))

[[7 0 5]
 [0 1 9]]


In [9]:
print(a + 2*np.transpose(c))

[[-3  4  3]
 [ 2 -1  5]]


In [12]:
#Задача2 Создать матрицу размером 8х8 элементов, состоящуюизнулей. Заполнить эту матрицу значениями, расположенными в шахматном порядке
a = np.zeros((8,8),int)
a[::2,::2]=1
a[1::2,1::2]=1
print(a)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [13]:
'''Задача3*
1.Сформировать два вектора: первый длиной 15 элементов со значениями от 0 до 1,4 с шагом 0,1 ;второй–длиной 6 элементов созначениями от 1 до 6.
2.Преобразовать первый вектор в матрицу 5х3,а второй– в матрицу 3х2. Выполнить перемножение этих матриц. Сами матрицы и результат их перемножения вывести на экран.'''
import numpy as np


a = np.matrix(np.arange(0,1.5,0.1).reshape(5, 3))
b = np.matrix(np.arange(6).reshape(3, 2))
print(a)
print(b)
print(a*b)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[0 1]
 [2 3]
 [4 5]]
[[ 1.   1.3]
 [ 2.8  4. ]
 [ 4.6  6.7]
 [ 6.4  9.4]
 [ 8.2 12.1]]


In [14]:
'''Задача4*
1.Сформировать вектор из целых чисел(тип элементов должен быть int32) размерностью 36 и значениями 1,3,5,7, ... и так далее.
2.Выделить из этого вектора все элементы со значениями кратными 3. Вывести результат на экран (исходный вектор и с кратными числами).'''

import numpy as np

a = np.matrix([x for x in range(1,36,2)],np.int32)
print(a)
b = []
x = np.shape(a[0])

for x in range(x[1]):
  if a[0,x] % 3 == 0:
    b.append(a[0,x])
print(b)

#получилось криво, но работает, был бы рад увидеть правильное и изящное решение данной задачи

[[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35]]
[3, 9, 15, 21, 27, 33]
